CREATE TABLE [dbo].[VENTA]
(
[IDVEN] [int] NOT NULL IDENTITY(1, 1),
[FECVEN] [date] NOT NULL CONSTRAINT [DF__VENTA__FECVEN__276EDEB3] DEFAULT (getdate()),
[TIPVEN] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[IDCLI] [int] NOT NULL,
[IDTRA] [int] NOT NULL,
[ESTVEN] [char] (1) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF__VENTA__ESTVEN__286302EC] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_pk] PRIMARY KEY CLUSTERED ([IDVEN]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_CLIENTE] FOREIGN KEY ([IDCLI]) REFERENCES [dbo].[CLIENTE] ([IDCLI])
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_TRABAJADOR] FOREIGN KEY ([IDTRA]) REFERENCES [dbo].[TRABAJADOR] ([IDTRA])
GO
