CREATE TABLE [dbo].[TRABAJADOR]
(
[IDTRA] [int] NOT NULL IDENTITY(1, 1),
[NOMTRA] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[APETRA] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[DNITRA] [char] (8) COLLATE Latin1_General_CI_AS NOT NULL,
[CELTRA] [char] (9) COLLATE Latin1_General_CI_AS NOT NULL,
[ESTTRA] [char] (1) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF__TRABAJADO__ESTTR__37A5467C] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRABAJADOR] ADD CONSTRAINT [TRABAJADOR_pk] PRIMARY KEY CLUSTERED ([IDTRA]) ON [PRIMARY]
GO
