CREATE TABLE [dbo].[CLIENTE]
(
[IDCLI] [int] NOT NULL IDENTITY(1, 1),
[NOMCLI] [varchar] (40) COLLATE Latin1_General_CI_AS NOT NULL,
[APECLI] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[DNICLI] [char] (8) COLLATE Latin1_General_CI_AS NOT NULL,
[CELCLI] [char] (9) COLLATE Latin1_General_CI_AS NOT NULL,
[EMACLI] [varchar] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[DOMCLI] [varchar] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[CODUBI] [char] (6) COLLATE Latin1_General_CI_AS NOT NULL,
[ESTCLI] [char] (1) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF__CLIENTE__ESTCLI__31EC6D26] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [CLIENTE_pk] PRIMARY KEY CLUSTERED ([IDCLI]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [CLIENTE_UBIGEO] FOREIGN KEY ([CODUBI]) REFERENCES [dbo].[UBIGEO] ([CODUBI])
GO
