CREATE TABLE [dbo].[RESERVA_DETALLE]
(
[IDRESDET] [int] NOT NULL IDENTITY(1, 1),
[IDRES] [int] NOT NULL,
[IDPRO] [int] NOT NULL,
[CANPLARESDET] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RESERVA_DETALLE] ADD CONSTRAINT [RESERVA_DETALLE_pk] PRIMARY KEY CLUSTERED ([IDRESDET]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RESERVA_DETALLE] ADD CONSTRAINT [RESERVA_DETALLE_PRODUCTO] FOREIGN KEY ([IDPRO]) REFERENCES [dbo].[PRODUCTO] ([IDPRO])
GO
ALTER TABLE [dbo].[RESERVA_DETALLE] ADD CONSTRAINT [RESERVA_DETALLE_RESERVA] FOREIGN KEY ([IDRES]) REFERENCES [dbo].[RESERVA] ([IDRES])
GO
