CREATE TABLE [dbo].[VENTA_DETALLE]
(
[IDVENDET] [int] NOT NULL IDENTITY(1, 1),
[IDPRO] [int] NOT NULL,
[CANTVENDET] [int] NOT NULL,
[IDVEN] [int] NOT NULL,
[ESTVENDET] [char] (1) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF__VENTA_DET__ESTVE__24927208] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_pk] PRIMARY KEY CLUSTERED ([IDVENDET]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_PRODUCTO] FOREIGN KEY ([IDPRO]) REFERENCES [dbo].[PRODUCTO] ([IDPRO])
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_VENTA] FOREIGN KEY ([IDVEN]) REFERENCES [dbo].[VENTA] ([IDVEN])
GO
