CREATE TABLE [dbo].[RESERVA]
(
[IDRES] [int] NOT NULL IDENTITY(1, 1),
[IDCLI] [int] NOT NULL,
[IDTRA] [int] NOT NULL CONSTRAINT [DF__RESERVA__IDTRA__2D27B809] DEFAULT ('1'),
[FECREGRES] [datetime] NOT NULL CONSTRAINT [DF__RESERVA__FECREGR__2E1BDC42] DEFAULT (getdate()),
[FECDESRES] [smalldatetime] NULL,
[CANPERRES] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[MONINIRES] [decimal] (4, 2) NULL,
[ESTRES] [char] (1) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF__RESERVA__ESTRES__2F10007B] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RESERVA] ADD CONSTRAINT [RESERVA_pk] PRIMARY KEY CLUSTERED ([IDRES]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RESERVA] ADD CONSTRAINT [RESERVA_CLIENTE] FOREIGN KEY ([IDCLI]) REFERENCES [dbo].[CLIENTE] ([IDCLI])
GO
ALTER TABLE [dbo].[RESERVA] ADD CONSTRAINT [RESERVA_TRABAJADOR] FOREIGN KEY ([IDTRA]) REFERENCES [dbo].[TRABAJADOR] ([IDTRA])
GO
