CREATE TABLE [dbo].[PRODUCTO]
(
[IDPRO] [int] NOT NULL IDENTITY(1, 1),
[NOMPRO] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[DESPRO] [varchar] (200) COLLATE Latin1_General_CI_AS NOT NULL,
[PREPRO] [decimal] (4, 2) NOT NULL,
[CATPRO] [char] (4) COLLATE Latin1_General_CI_AS NOT NULL,
[STOPRO] [int] NOT NULL,
[ESTPRO] [char] (1) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF__PRODUCTO__ESTPRO__34C8D9D1] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_pk] PRIMARY KEY CLUSTERED ([IDPRO]) ON [PRIMARY]
GO
