CREATE TABLE [dbo].[UBIGEO]
(
[CODUBI] [char] (6) COLLATE Latin1_General_CI_AS NOT NULL,
[DEPUBI] [varchar] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[PROVUBI] [char] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[DISTUBI] [varchar] (80) COLLATE Latin1_General_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UBIGEO] ADD CONSTRAINT [UBIGEO_pk] PRIMARY KEY CLUSTERED ([CODUBI]) ON [PRIMARY]
GO
